title: Lenus
url: https://lenus-sss.github.io
baseurl: ""
markdown: kramdown

collections:
  experience:
    output: true
    permalink: /experience/:name/
  experiments:
    output: true
    permalink: /experiments/:name/
  thoughts:
    output: true
    permalink: /thoughts/:name/

defaults:
  - scope:
      path: ""
      type: experience
    values:
      layout: article
  - scope:
      path: ""
      type: experiments
    values:
      layout: article
  - scope:
      path: ""
      type: thoughts
    values:
      layout: article
